theme: jekyll-theme-cayman
title: Speedy Spanish
description: Refresh your Spanish Skills

github: 
  Vocabulary: Vocabulary.html
  Numbers: Numbers.html
  Reading: Reading.html
  More: More.html
  Clothing: Clothing.html
  Calendar: Calendar.html
  Verbs: Verbs.html
