theme: jekyll-theme-cayman
title: Speedy Spanish Refresh
description: Refresh your Spanish Skills

github: 
  Vocabulary: Vocabulary.html
  Numbers: Numbers.html
  Reading: Reading.html
  More: More.html
