theme: jekyll-theme-cayman
title: Speedy Spanish Refresh
description: Final project for SML5202, by Elise Bargman Fall 2019
github: 
  Vocabulary: Vocabulary.html
  Page3: Page3.html
  Page4: Page4.html
  Exercises: Exercises.html
  JavaScript: JavaScriptPractice.html
