theme: jekyll-theme-cayman
title: Speedy Spanish Refresh
description: Final project for SML5202, by Elise Bargman Fall 2019
github: 
  Vocabulary: Vocabulary.html
  Numbers: Numbers.html
  Reading: Reading.html
  More: More.html
